#!/bin/bash

# Check if the .env file exists
if [ -f .env ]; then
  # Enable auto-export
  set -a
  source .env
  # Disable auto-export
  set +a
else
  echo "Error: .env file not found!"
  exit 1
fi

echo "🚀 Starting deployment to $REMOTE_HOST..."

rsync -avzh --delete ./dist/* -e "ssh -p $REMOTE_PORT -i $REMOTE_SSH_KEY_PATH" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_DEST"

echo "✅ Deployment complete!"